library(feather)
library(data.table)
library(dplyr)
library(tidyr)
library(shiny)
library(DT)
library(highcharter)
library(shinythemes)
library(shinyjs)
library(cellbaseR)
library(shinyWidgets)
cb <- CellBaseR()
aug <- read_feather('/home/sieny/Omni/Done/SGP/Final.feather',columns = c(
  'rs', 'Chr', 'Start', 'REF', 'ALT', 'conseq', 'Impact', 'HGNC',
  'ENSEMBL', 'Arb_MAF', 'Nub_MAF','Eas_MAF','Wes_MAF','Sot_MAF','NE_MAF','SW_MAF'
))
aug <- as.data.table(aug)
setindexv(aug, c('Chr', 'Impact','HGNC','conseq','ENSEMBL','rs'))
# hugo <- fread('/home/sieny/Omni/Done/SGP/hugo_approved.tsv')
genes <- unique(aug$HGNC)
# genes <- sort(genes)
